name: CMake CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Boost (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libpq-dev libpqxx-dev libbenchmark-dev

      - name: Install Boost (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install boost libpq libpqxx google-benchmark
          brew link --force libpq

      - name: Install Boost libraries (Windows)
        if: matrix.os == 'windows-latest'
        id: install-boost
        uses: MarkusJx/install-boost@v2.5.1
        with:
          boost_version: 1.83.0
          toolset: msvc
          cache: true
          libs: "all"
          link: static

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
      

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest --output-on-failure